env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  jsx-quotes:
    - 2
    - prefer-single
  keyword-spacing:
    - 2
    - before: true
      after: true
  eqeqeq:
    - error
    - smart
overrides:
  - files: ["**/*.ts?(x)"]
    rules:
      no-console: error
